### ISSUE TITLE
Games still freeze with multi audio output on mac

### ISSUE THREAD

**Issue by MisuYamaneko** [OpenEmu/OpenEmu-Update#6]
First of all I would like to thank you for creating something like Open emu which as a lot of emulators working in one program, It's reallly great!

The new updated states that the mac audio multi output issue was resolved, but If I try to launch ANY game with audio multi output on, the game will freeze and won't work at all. I can't even close the window, It's like the whole program freeze. 
I'm using Mac 14.14.5.

However It is working with Loopback sound, too bad It's not a free program and is rather expensive.

**Comment by clobber** [comment]
Problems for the application do not go here, they go in the [main repo](https://github.com/OpenEmu/OpenEmu/) so you will have to open a new issue there and elaborate on your problem in great detail. We solved this problem for all the issues we had reports for and users confirmed it was fixed. Your particular case may be an edge case that we were unable to test.
