### ISSUE TITLE
Loss of Full Screen after Update

### ISSUE THREAD

**Issue by EdGeinsMother** [OpenEmu/OpenEmu-Update#7]
Unable to do full screen view for games after update. Window expands but video retains original dimensions and resolution.

Running v2.3 on Mac OS 10.15.7

**Comment by shysaur** [comment]
Do not post application-related issues on this repository. Use github.com/OpenEmu/OpenEmu/issues.

Anyway, this behaviour is intentional. To bring back how it worked before 2.3, go in Preferences and disable "Always snap popout gameplay window to integer scale".
